# Generated by Django 5.2.8 on 2026-02-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='impact',
        ),
    ]
