# Generated by Django 5.2.9 on 2025-12-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('collection', models.CharField(blank=True, max_length=100, verbose_name='Коллекция')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('width', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Высота (см)')),
                ('depth', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Глубина (см)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
